### PR TITLE
new changes

### PR DESCRIPTION
**Pull request by tejpoudel**

### CODE REVIEW

**Comment by tejpoudel** [comment]
@rohitchhetri can you please review it.

**Review by rohitchhetri — DISMISSED** [review]

**Comment by rohitchhetri** [comment]
Done

**Comment by tejpoudel** [comment]
idkf

**Comment by treenah** [comment]
changes to bg and nav colors

**Review by treenah — DISMISSED** [review]

**Review by rohitchhetri — APPROVED** [review]

**Pull request merged**
